repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: visualize
          name: update visuals
          entry: poetry run python -m stats.visualize
          language: system
          always_run: true
          pass_filenames: false
