* January Training Log
** 01-26-2023
Afternoon jog with Jasper. Watch still not working so no heart rate date.
Felt a little tight in the left knee but it is loosening up.

** 01-24-2023
Went on an evening bike ride. Felt pretty tired but wanted to get out anyway.
Left Knee was a little sore, but no longer hurst when getting out of the
saddle at different angles. It's been fun to try to find places to do balance
practice. There is a small amphitheater near the Henley bridge with some
good concrete strips to practice on.

** 01-23-2023
Went on an evening jog, watch died half way through so didn't get heart rate
data. Felt a bit stiff the whole time and a bit drained too. Didn't feel like
I spent that much time in zone 3. Could be a recovery issue from skiing.

** 01-21-2023
Went on an afternoon trail jog with jasper. Lots of stopping because he
really wanted to smell things. In the evening I went to Cataloochie ski
area for the first time. Was happy because my left knee didn't hurt much
the entire time. Seems like running more and biking more are helping my knee
feel better. Perhaps it was a strength issue.

** 01-19-2023
Went on an evening bike ride to downtown and back. Previously my left knee was
a little sore when changing to certain standing positions, but felt mostly good
tonight. It's interesting that on flats, I have a hard time getting my heart rate
into zone 3 but on any hill, I got almost to zone 4.

** 01-18-2023
Went on an evening job. Since it was dark, I ran on the greenway. Heart rate stayed
within zone 2 and zone 3 most of the way so I was able to jog continuously through mile 1.
Calves felt a little tight and felt like I was exerting myself more than previous runs.

** 01-17-2023
Went on an afternoon jog. Good sensations in the legs, but felt heavy afterward. Was winded quickly
when going up hill so lots of walking to achieve my goal of training mostly in heart rates zones 2
and 3 (preference for 3).
